text_cartlogo="xpath://a[@href='https://www.bookswagon.com/shoppingcart.aspx']//span[@class='itemcount']"
text_book="xpath://a[normalize-space()='Book']"
text_fiction="xpath://ul[@class='list-unstyled maincategory dropdown']//a[@onclick='getSearchResult()'][normalize-space()='Fiction']"
text_bookname="xpath://a[normalize-space()='The Hidden Hindu']"
text_addtocartbook="xpath://a[@id='btnAddtocart']"
text_movetowishlist="id:ctl00_phBody_BookCart_lvCart_ctrl0_btnMovetoWishlist"
text_remove="id:ctl00_phBody_BookCart_lvCart_ctrl0_imgDelete"
text_Buy="id:ctl00_phBody_BookCart_lvCart_imgPayment"
text_currencydropdown="id:ctl00_phBody_ddlCurrency"
text_INRcurrency="xpath://*[@id='ctl00_phBody_ddlCurrency']/option[1]"
text_USDcurrency="xpath://*[@id='ctl00_phBody_ddlCurrency']/option[2]"
text_totalgross="id:ctl00_phBody_BookCart_lvCart_lblTotalGross"
text_add="name:ctl00$phBody$BookCart$lvCart$ctrl0$btnPlus"
text_minus="xpath://input[@id='ctl00_phBody_BookCart_lvCart_ctrl0_btnMinus']"
text_totalcartitem="id:ctl00_phBody_BookCart_lvCart_lblCartItems"
text_selectedcurrency="xpath://option[@selected='selected']"
text_itemcount="id:ctl00_phBody_BookCart_lvCart_ctrl0_txtQty"
text_cartitemlogo="id:ctl00_lblTotalCartItems"
text_bookimage="xpath://img[@alt='The Hidden Hindu']"
text_wishlistitemcount="id:ctl00_lblWishlistCount"
text_newarrival="xpath://li[@id='ctl00_linewrelease']//a[contains(text(),'New Arrivals')]"
text_feelbook="xpath://div[@class='row']//div[3]//div[1]//a[1]//img[1]"
text_boxset="xpath://li[@id='ctl00_lipreorder']//a[contains(text(),'Box Sets')]"
text_setofbook="xpath://img[@alt='Tintin Paperback Boxed Set 23 titles'][1]"
text_bestseller="xpath://li[@id='ctl00_libestseller']//a[contains(text(),'Best sellers')]"
text_bestsellerbook="xpath://img[@alt='Atomic Habits'][1]"
text_fictionbook="xpath://a[normalize-space()='Fiction Books']"
text_fictionbookname="xpath://div[4]//a[1]//div[1]"
text_awardwinner="xpath://li[@id='ctl00_liAW']//a[contains(text(),'Award Winners')]"
text_awarswinnerbook="xpath://img[@alt='Red, White & Royal Blue'][1]"
text_featuredauthor="xpath://li[@id='ctl00_liRequestBook']//a[normalize-space()='Featured Authors']"
text_authorname="xpath://a[normalize-space()='Arundhati Roy']"
text_authorbook="xpath://a[normalize-space()='God of Small Things']"
text_todaydeal="xpath://*[@id='ctl00_li4']/a"
text_todaydealbook="xpath://img[@alt='Red Queen']"
text_searchbox="xpath://input[@id='inputbar']"
text_searchbutton="xpath://input[@id='btnTopSearch']"
text_searchresultbook="xpath://a[normalize-space()='God of Small Things']"

