text_myaccountarrow="xpath://div[@class='arrowimg']"
text_login="xpath://a[normalize-space()='Log in']"
text_mobile="id:ctl00_phBody_SignIn_txtEmail"
text_password="id:ctl00_phBody_SignIn_txtPassword"
text_loginbutton= "id:ctl00_phBody_SignIn_btnLogin"
text_requestotp="id:ctl00_phBody_SignIn_btnRequestOTP"
text_forgotpassword="xpath://a[normalize-space()='Forgot your Password?']"
text_signup="xpath://div[@class='form-group col-sm-12']//a[@class='themecolor d-block w-100 mb-3 font-weight-bold signuplink'][normalize-space()='New to Bookswagon? Sign up']"
text_googleicon="xpath://div[@id='ctl00_phBody_SignIn_plnLoginPassword']//img[@title='Login with Google']"