text_name = "id:ctl00_phBody_SignUp_txtName"
text_mobilenumber = "id:ctl00_phBody_SignUp_txtEmail"
text_captcha="id:recaptcha-anchor"
text_continuebutton="id:ctl00_phBody_SignUp_btnContinue"
text_existinguser="xpath://a[normalize-space()='Existing User? Log in']"
text_google="xpath://div[contains(@class,'signup-wrapper')]//div//img[contains(@title,'Login with Google')]"
text_unsubscribe="id:ctl00_phBody_SignUp_chkNewsletter"
text_countrycode="id:ctl00_phBody_SignUp_ddlCountryMobileCode"